version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anketnica-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend/anketi.db:/app/dist/anketi.db
    restart: unless-stopped