version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: anketnica-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/anketi.db:/app/anketi.db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: anketnica-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  vk-tunnel:
    build:
      context: .
      dockerfile: Dockerfile.vk-tunnel
    container_name: anketnica-vk-tunnel
    depends_on:
      - frontend
    network_mode: "host"
    restart: unless-stopped